root: true

parserOptions:
  ecmaVersion: 2020
  project: ['./tsconfig.json']
  tsconfigRootDir: '.'

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

extends:
  - 'standard-with-typescript'
  - 'prettier/@typescript-eslint'

overrides:
  - files:
      - './**/__test__/*.test.ts'
    rules:
      '@typescript-eslint/no-unused-expressions': 'off'
