version: 2.1
executors:
  node-14_16_0:
    docker:
      - image: circleci/node:14.16.0

parameters:
  node_modules_cache_key:
    type: string
    default: perkulator-node_modules-{{checksum "package-lock.json"}}

jobs:
  install:
    executor: node-14_16_0
    steps:
      - restore_cache:
          key: << pipeline.parameters.node_modules_cache_key >>
      - run: npm install --no-audit --no-fund
      - save_cache:
          key: << pipeline.parameters.node_modules_cache_key >>
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules

  lint:
    executor: node-14_16_0
    steps:
      - run:
          name: Linting code
          command: npm run lint
  typeCheck:
    executor: node-14_16_0
    steps:
      - run:
          name: Type check code
          command: npm run typeCheck
  unitTest:
    executor: node-14_16_0
    steps:
      - run:
          name: Unit test
          command: npm run test-unit

workflows:
  version: 2
  init:
    jobs:
      - install
  preTest:
    jobs:
      - lint:
          requires:
            - init
      - typeCheck:
          requires:
            - init
